services:
  solr:
    image: solr:latest
    container_name: solr-server
    ports:
      - "8983:8983"
    environment:
      - SOLR_HOME=/var/solr/data
      - SOLR_HEAP=1g # Memory size of the solr heap (optional)
    volumes:
      - solrdata:/var/solr
    command: 
      - solr-precreate
      - core # Core name

volumes:
  solrdata:
    driver: local